{
  Throwable failure=new RuntimeException();
  BuildResult result=new BuildResult(null,failure);
  try {
    result.rethrowFailure();
    fail();
  }
 catch (  GradleException e) {
    assertThat(e.getMessage(),equalTo("Build aborted because of an internal error."));
    assertThat(e.getCause(),sameInstance(failure));
  }
}
