{
  RuntimeException failure=new RuntimeException("x");
  getTask().doFirst(createExceptionAction(new InvokerInvocationException(failure)));
  checkException(failure);
}
