{
  final RuntimeException failure=new RuntimeException();
  Bean bean=new Bean(){
    void failure(){
      throw failure;
    }
  }
;
  try {
    bean.invokeMethod("failure");
    fail();
  }
 catch (  Exception e) {
    assertThat(e,sameInstance((Exception)failure));
  }
}
