{
  final Throwable failure=context.mock(TestException.class);
  context.checking(new Expectations(){
{
      allowing(failure).getCause();
      will(returnValue(null));
      allowing(failure).getStackTrace();
      will(returnValue(WrapUtil.toArray(element)));
    }
  }
);
  DefaultExceptionAnalyser analyser=analyser();
  notifyAnalyser(analyser,source);
  assertThat(analyser.transform(failure),sameInstance(failure));
}
