{
  final RuntimeException failure=new RuntimeException("<message>");
  context.checking(new Expectations(){
{
      one(logger).error(with(containsString("Build aborted because of an internal error.")),with(sameInstance(failure)));
    }
  }
);
  reporter.buildFinished(HelperUtil.createBuildResult(failure));
}
