{
  final RuntimeException failure=new RuntimeException("<message>");
  context.checking(new Expectations(){
{
      one(logger).error(with(containsString("Build aborted anormally because of an internal error.")));
      one(logger).error("Exception is:",failure);
    }
  }
);
  reporter.buildFinished(new BuildResult(null,failure));
}
